### ISSUE TITLE
Panic when moving the joystick (saitek)

### ISSUE THREAD

**Issue by rami-dabain** [splace/joysticks#1]
`goroutine 1 [select]:
main.main()
	/home/xx/Workspace/go/src/xx/joystick/main.go:18 +0x333

goroutine 5 [chan send]:
github.com/splace/joysticks.eventPipe(0x4ea0e0, 0xc420032020, 0xc4200180c0)
	/home/xx/Workspace/go/src/github.com/splace/joysticks/joysticks_linux.go:91 +0xfc
created by github.com/splace/joysticks.Connect
	/home/xx/Workspace/go/src/github.com/splace/joysticks/joysticks_linux.go:55 +0x4b7

goroutine 7 [chan send]:
github.com/splace/joysticks.HID.ParcelOutEvents(0xc4200180c0, 0xc420010390, 0xc4200103c0, 0xc4200103f0, 0xc420010420, 0xc420010450, 0xc420010480, 0xc4200104b0, 0xc4200104e0, 0xc420010510, ...)
	/home/xx/Workspace/go/src/github.com/splace/joysticks/joysticks.go:132 +0x720
created by github.com/splace/joysticks.Capture
	/home/xx/Workspace/go/src/github.com/splace/joysticks/joysticks_linux.go:34 +0xd7
exit status 2
`

**Comment by splace** [comment]
could you supply the main.go, and the error?

(your listing is just the go-routines that were still running when the program ended.)

be interesting to test this code on an actual joystick, the underlying Linux kernel code calls everything a "joystick", controllers/gamepads/joysticks etc., i just followed that naming, perhaps i should make it clearer that it should handle them all, but i only have a play-station type controller myself.

**Comment by rami-dabain** [comment]
I have used your example. nothing edited

**Comment by splace** [comment]
the 'play' example is for a play-station controller, and plays notes when you press buttons, or move the hats, using the command executable 'aplay'.

it should panic with a reasonable error message, if 'aplay' isn't installed.

also, it panics if there is no joystick recognised by the kernel, (kernel might not be compiled with support, but that seems to be very rare.)  but in that case you should get "panic: runtime error: index out of range"  ie you tried to use joystick #1 from a slice of available joysticks of zero length.

but AFAIK, there should always be more info than the go-routine dump.

i'll add a simpler generic example, something that lists buttons/hats and just prints events.

**Comment by splace** [comment]
now has a basic example, and the readme example is similarly basic.

**Comment by splace** [comment]
closing issue, can't do much without the actual error message.
